# touk-url:prod
FROM touk/url:core

ENV APPROOT http://localhost:3000
ENV PORT 3000

ENV PGUSER touk-url
ENV PGPASS touk-url
ENV PGHOST postgres-db
#RUN mkdir -p /var/log/touk-url
#ENV LOGFILE /var/log/touk-url/current.log
#ENV PGPORT 5432
#ENV PGDATABASE touk-url
#ENV PGPOOLSIZE 20
