Default: &defaults
  database: touk-url.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: touk-url_test.sqlite3
  <<: *defaults

Staging:
  database: touk-url_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: touk-url_production.sqlite3
  poolsize: 100
  <<: *defaults
